# -*- mode: ruby -*-
# vi: set ft=ruby :

require "rbconfig"
IS_WINDOWS = (RbConfig::CONFIG["host_os"] =~ /mswin|mingw|cygwin/) ? true : false
M2_HOME = "../.m2"

Vagrant.configure("2") do |config|

  # Define our box
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.hostname = "geonetwork-vm"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine
  config.vm.network :forwarded_port, guest: 8080, host: 8080, auto_correct: true  # embedded jetty server

  # Share additional folders to the guest VM
  config.vm.synced_folder "../src", "/home/vagrant/src", :nfs => !IS_WINDOWS
  config.vm.synced_folder M2_HOME, "/home/vagrant/.m2", :nfs => !IS_WINDOWS

  # VirtualBox configuration
  config.vm.provider :virtualbox do |vb|

    # Use VBoxManage to customize the VM
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/src", "1"]
  end

  # Provisioning with chef solo
  config.vm.provision :chef_solo do |chef|
    #chef.log_level = :debug
    chef.add_recipe "apt"
    chef.add_recipe "java"
    chef.add_recipe "ark"
    chef.add_recipe "ant"
    chef.add_recipe "maven"
    chef.add_recipe "python"

    chef.json = {
      :java => {
        :install_flavor => "oracle",
        :jdk_version => "7",
        :oracle => {
          :accept_oracle_download_terms => true
        }
      },
      :ant => {
        :install_method => "package"
      },
      :maven => {
        :version => "3",
        :url => "http://mirror.catn.com/pub/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz",
        :checksum => "6e3e9c949ab4695a204f74038717aa7b2689b1be94875899ac1b3fe42800ff82"
      }
    }
  end

  # Enable provisioning with shell using a bash script
  config.vm.provision :shell, :path => "provision.sh"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network :public_network
end
